import type {
  SolicitacaoRow,
  CotacaoRow,
  CotacaoItemRow,
  PedidoRow,
  PedidoItemRow,
  ProdutoOption,
} from './compras'

export const mockProdutos: ProdutoOption[] = [
  { id: 'p001', nome: 'Luminária Pendente Cristal 3Lâmpadas', codigo_produto: 301 },
  { id: 'p002', nome: 'Spot LED Embutir 7W 2700K', codigo_produto: 7 },
  { id: 'p003', nome: 'Fita LED 24V 14.4W/m IP65', codigo_produto: 24 },
  { id: 'p004', nome: 'Lustre Cascata Cristal 60cm', codigo_produto: 60 },
  { id: 'p008', nome: 'Driver LED 12V 150W', codigo_produto: 150 },
]

export const mockSolicitacoes: SolicitacaoRow[] = [
  {
    id: 's1',
    produto_id: 'p002',
    produto_nome: 'Spot LED Embutir 7W 2700K',
    produto_codigo: 7,
    quantidade: 25,
    prioridade: 'alta',
    observacao: 'Urgente — projeto OB-2024-007',
    status: 'em_cotacao',
    criado_em: '2026-07-08T10:00:00Z',
  },
  {
    id: 's2',
    produto_id: 'p003',
    produto_nome: 'Fita LED 24V 14.4W/m IP65',
    produto_codigo: 24,
    quantidade: 30,
    prioridade: 'alta',
    observacao: null,
    status: 'aberta',
    criado_em: '2026-07-09T14:00:00Z',
  },
  {
    id: 's3',
    produto_id: 'p001',
    produto_nome: 'Luminária Pendente Cristal 3Lâmpadas',
    produto_codigo: 301,
    quantidade: 6,
    prioridade: 'normal',
    observacao: 'Reposição de estoque',
    status: 'pedido_gerado',
    criado_em: '2026-07-05T09:30:00Z',
  },
  {
    id: 's4',
    produto_id: 'p008',
    produto_nome: 'Driver LED 12V 150W',
    produto_codigo: 150,
    quantidade: 11,
    prioridade: 'normal',
    observacao: null,
    status: 'aberta',
    criado_em: '2026-07-10T08:00:00Z',
  },
  {
    id: 's5',
    produto_id: 'p004',
    produto_nome: 'Lustre Cascata Cristal 60cm',
    produto_codigo: 60,
    quantidade: 2,
    prioridade: 'baixa',
    observacao: 'Cliente solicitou antecipação',
    status: 'em_cotacao',
    criado_em: '2026-07-07T11:00:00Z',
  },
]

export const mockCotacoes: CotacaoRow[] = [
  {
    id: 'c1',
    numero: 'COT-20260708-0001',
    fornecedor_id: 'f1',
    fornecedor_nome: 'Distribuidora Luz SP',
    status: 'em_andamento',
    validade: '2026-07-20',
    condicoes_pagamento: '30/60 dias',
    observacao: null,
    criado_em: '2026-07-08T10:30:00Z',
  },
  {
    id: 'c2',
    numero: 'COT-20260709-0002',
    fornecedor_id: 'f3',
    fornecedor_nome: 'TecnoLED Brasil',
    status: 'em_andamento',
    validade: '2026-07-25',
    condicoes_pagamento: 'À vista com 5% desc.',
    observacao: 'Aguardando confirmação de prazo',
    criado_em: '2026-07-09T15:00:00Z',
  },
  {
    id: 'c3',
    numero: 'COT-20260705-0003',
    fornecedor_id: 'f2',
    fornecedor_nome: 'Importadora Crystal',
    status: 'pedido_gerado',
    validade: '2026-07-15',
    condicoes_pagamento: '45 dias',
    observacao: null,
    criado_em: '2026-07-05T10:00:00Z',
  },
]

export const mockCotacaoItens: Record<string, CotacaoItemRow[]> = {
  c1: [
    {
      id: 'ci1',
      cotacao_id: 'c1',
      produto_id: 'p002',
      produto_nome: 'Spot LED Embutir 7W 2700K',
      quantidade: 25,
      custo_unitario: 18.5,
      prazo_entrega_dias: 15,
    },
    {
      id: 'ci2',
      cotacao_id: 'c1',
      produto_id: 'p008',
      produto_nome: 'Driver LED 12V 150W',
      quantidade: 11,
      custo_unitario: 85.0,
      prazo_entrega_dias: 15,
    },
  ],
  c2: [
    {
      id: 'ci3',
      cotacao_id: 'c2',
      produto_id: 'p003',
      produto_nome: 'Fita LED 24V 14.4W/m IP65',
      quantidade: 30,
      custo_unitario: 32.0,
      prazo_entrega_dias: 20,
    },
    {
      id: 'ci4',
      cotacao_id: 'c2',
      produto_id: 'p004',
      produto_nome: 'Lustre Cascata Cristal 60cm',
      quantidade: 2,
      custo_unitario: 450.0,
      prazo_entrega_dias: 30,
    },
  ],
  c3: [
    {
      id: 'ci5',
      cotacao_id: 'c3',
      produto_id: 'p001',
      produto_nome: 'Luminária Pendente Cristal 3Lâmpadas',
      quantidade: 6,
      custo_unitario: 280.0,
      prazo_entrega_dias: 25,
    },
  ],
}

export const mockPedidos: PedidoRow[] = [
  {
    id: 'pc1',
    numero: 'PC-20260705-0001',
    fornecedor_id: 'f2',
    fornecedor_nome: 'Importadora Crystal',
    status: 'enviado',
    data_emissao: '2026-07-05',
    data_prevista_entrega: '2026-07-30',
    valor_total: 1680.0,
    condicoes_pagamento: '45 dias',
  },
  {
    id: 'pc2',
    numero: 'PC-20260703-0002',
    fornecedor_id: 'f1',
    fornecedor_nome: 'Distribuidora Luz SP',
    status: 'parcialmente_recebido',
    data_emissao: '2026-07-03',
    data_prevista_entrega: '2026-07-18',
    valor_total: 925.0,
    condicoes_pagamento: '30/60 dias',
  },
  {
    id: 'pc3',
    numero: 'PC-20260701-0003',
    fornecedor_id: 'f4',
    fornecedor_nome: 'Materiais Elétricos Silva',
    status: 'rascunho',
    data_emissao: '2026-07-01',
    data_prevista_entrega: null,
    valor_total: null,
    condicoes_pagamento: null,
  },
  {
    id: 'pc4',
    numero: 'PC-20260628-0004',
    fornecedor_id: 'f3',
    fornecedor_nome: 'TecnoLED Brasil',
    status: 'recebido',
    data_emissao: '2026-06-28',
    data_prevista_entrega: '2026-07-12',
    valor_total: 2400.0,
    condicoes_pagamento: 'À vista',
  },
]

export const mockPedidoItens: Record<string, PedidoItemRow[]> = {
  pc1: [
    {
      id: 'pi1',
      pedido_id: 'pc1',
      produto_id: 'p001',
      produto_nome: 'Luminária Pendente Cristal 3Lâmpadas',
      quantidade: 6,
      qtd_recebida: 0,
      custo_unitario: 280.0,
    },
  ],
  pc2: [
    {
      id: 'pi2',
      pedido_id: 'pc2',
      produto_id: 'p002',
      produto_nome: 'Spot LED Embutir 7W 2700K',
      quantidade: 40,
      qtd_recebida: 25,
      custo_unitario: 18.5,
    },
    {
      id: 'pi3',
      pedido_id: 'pc2',
      produto_id: 'p008',
      produto_nome: 'Driver LED 12V 150W',
      quantidade: 5,
      qtd_recebida: 0,
      custo_unitario: 85.0,
    },
  ],
  pc3: [
    {
      id: 'pi4',
      pedido_id: 'pc3',
      produto_id: 'p003',
      produto_nome: 'Fita LED 24V 14.4W/m IP65',
      quantidade: 50,
      qtd_recebida: 0,
      custo_unitario: 32.0,
    },
  ],
  pc4: [
    {
      id: 'pi5',
      pedido_id: 'pc4',
      produto_id: 'p004',
      produto_nome: 'Lustre Cascata Cristal 60cm',
      quantidade: 5,
      qtd_recebida: 5,
      custo_unitario: 450.0,
    },
    {
      id: 'pi6',
      pedido_id: 'pc4',
      produto_id: 'p001',
      produto_nome: 'Luminária Pendente Cristal 3Lâmpadas',
      quantidade: 2,
      qtd_recebida: 2,
      custo_unitario: 280.0,
    },
  ],
}
