import type { NecessidadeCompraRow, EntregaFuturaRow } from './necessidade-compra'

export const mockNecessidadeCompra: NecessidadeCompraRow[] = [
  {
    produto_id: 'p001',
    produto: 'Luminária Pendente Cristal 3Lâmpadas',
    produto_codigo: 'LPC-301',
    qtd_fisica: 2,
    qtd_comprometida: 8,
    necessidade_compra: 6,
    qtd_disponivel: 2,
    projetos_com_entrega_futura: 3,
  },
  {
    produto_id: 'p002',
    produto: 'Spot LED Embutir 7W 2700K',
    produto_codigo: 'SLE-7W',
    qtd_fisica: 15,
    qtd_comprometida: 40,
    necessidade_compra: 25,
    qtd_disponivel: 15,
    projetos_com_entrega_futura: 5,
  },
  {
    produto_id: 'p003',
    produto: 'Fita LED 24V 14.4W/m IP65',
    produto_codigo: 'FL-24V',
    qtd_fisica: 0,
    qtd_comprometida: 30,
    necessidade_compra: 30,
    qtd_disponivel: 0,
    projetos_com_entrega_futura: 4,
  },
  {
    produto_id: 'p004',
    produto: 'Lustre Cascata Cristal 60cm',
    produto_codigo: 'LCC-60',
    qtd_fisica: 1,
    qtd_comprometida: 3,
    necessidade_compra: 2,
    qtd_disponivel: 1,
    projetos_com_entrega_futura: 2,
  },
  {
    produto_id: 'p005',
    produto: 'Arandela Decorativa Bronze 1Lâmpada',
    produto_codigo: 'ADB-01',
    qtd_fisica: 5,
    qtd_comprometida: 12,
    necessidade_compra: 7,
    qtd_disponivel: 5,
    projetos_com_entrega_futura: 3,
  },
  {
    produto_id: 'p006',
    produto: 'Pendente Industrial Black 5Lâmpadas',
    produto_codigo: 'PIB-05',
    qtd_fisica: 3,
    qtd_comprometida: 10,
    necessidade_compra: 7,
    qtd_disponivel: 3,
    projetos_com_entrega_futura: 4,
  },
  {
    produto_id: 'p007',
    produto: 'Trilho Eletrificado 3 Fases 1m',
    produto_codigo: 'TRF-1M',
    qtd_fisica: 8,
    qtd_comprometida: 20,
    necessidade_compra: 12,
    qtd_disponivel: 8,
    projetos_com_entrega_futura: 6,
  },
  {
    produto_id: 'p008',
    produto: 'Driver LED 12V 150W',
    produto_codigo: 'DRV-150',
    qtd_fisica: 4,
    qtd_comprometida: 15,
    necessidade_compra: 11,
    qtd_disponivel: 4,
    projetos_com_entrega_futura: 5,
  },
]

export const mockEntregaFutura: Record<string, EntregaFuturaRow[]> = {
  p001: [
    {
      projeto_item_id: 'pi001',
      produto_id: 'p001',
      produto: 'Luminária Pendente Cristal 3Lâmpadas',
      produto_codigo: 'LPC-301',
      projeto_id: 'pr001',
      projeto_codigo: 'OB-2024-001',
      orcamento_id: 'oc001',
      orcamento_numero: 'ORC-001',
      cliente_id: 'c001',
      cliente: 'Maria Silva',
      q_venda: 4,
      q_entrega_futura: 4,
      q_reserva: 2,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-08T10:30:00Z',
    },
    {
      projeto_item_id: 'pi002',
      produto_id: 'p001',
      produto: 'Luminária Pendente Cristal 3Lâmpadas',
      produto_codigo: 'LPC-301',
      projeto_id: 'pr002',
      projeto_codigo: 'OB-2024-014',
      orcamento_id: 'oc002',
      orcamento_numero: 'ORC-014',
      cliente_id: 'c002',
      cliente: 'João Pereira',
      q_venda: 2,
      q_entrega_futura: 2,
      q_reserva: 0,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-09T14:00:00Z',
    },
  ],
  p002: [
    {
      projeto_item_id: 'pi003',
      produto_id: 'p002',
      produto: 'Spot LED Embutir 7W 2700K',
      produto_codigo: 'SLE-7W',
      projeto_id: 'pr003',
      projeto_codigo: 'OB-2024-007',
      orcamento_id: 'oc003',
      orcamento_numero: 'ORC-007',
      cliente_id: 'c003',
      cliente: 'Construtora Horizon',
      q_venda: 20,
      q_entrega_futura: 20,
      q_reserva: 15,
      q_transferida_saida: 5,
      atualizado_em: '2026-07-07T09:15:00Z',
    },
    {
      projeto_item_id: 'pi004',
      produto_id: 'p002',
      produto: 'Spot LED Embutir 7W 2700K',
      produto_codigo: 'SLE-7W',
      projeto_id: 'pr004',
      projeto_codigo: 'OB-2024-021',
      orcamento_id: 'oc004',
      orcamento_numero: 'ORC-021',
      cliente_id: 'c004',
      cliente: 'Ana Costa',
      q_venda: 20,
      q_entrega_futura: 20,
      q_reserva: 0,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-10T11:00:00Z',
    },
  ],
  p003: [
    {
      projeto_item_id: 'pi005',
      produto_id: 'p003',
      produto: 'Fita LED 24V 14.4W/m IP65',
      produto_codigo: 'FL-24V',
      projeto_id: 'pr005',
      projeto_codigo: 'OB-2024-010',
      orcamento_id: 'oc005',
      orcamento_numero: 'ORC-010',
      cliente_id: 'c005',
      cliente: 'Escritório Lima Arquitetura',
      q_venda: 30,
      q_entrega_futura: 30,
      q_reserva: 0,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-06T16:45:00Z',
    },
  ],
  p004: [
    {
      projeto_item_id: 'pi006',
      produto_id: 'p004',
      produto: 'Lustre Cascata Cristal 60cm',
      produto_codigo: 'LCC-60',
      projeto_id: 'pr006',
      projeto_codigo: 'OB-2024-018',
      orcamento_id: 'oc006',
      orcamento_numero: 'ORC-018',
      cliente_id: 'c006',
      cliente: 'Helena Souza',
      q_venda: 2,
      q_entrega_futura: 2,
      q_reserva: 1,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-05T08:20:00Z',
    },
  ],
  p005: [
    {
      projeto_item_id: 'pi007',
      produto_id: 'p005',
      produto: 'Arandela Decorativa Bronze 1Lâmpada',
      produto_codigo: 'ADB-01',
      projeto_id: 'pr007',
      projeto_codigo: 'OB-2024-003',
      orcamento_id: 'oc007',
      orcamento_numero: 'ORC-003',
      cliente_id: 'c007',
      cliente: 'Pedro Almeida',
      q_venda: 7,
      q_entrega_futura: 7,
      q_reserva: 5,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-04T13:30:00Z',
    },
  ],
  p006: [
    {
      projeto_item_id: 'pi008',
      produto_id: 'p006',
      produto: 'Pendente Industrial Black 5Lâmpadas',
      produto_codigo: 'PIB-05',
      projeto_id: 'pr008',
      projeto_codigo: 'OB-2024-025',
      orcamento_id: 'oc008',
      orcamento_numero: 'ORC-025',
      cliente_id: 'c008',
      cliente: 'Mariana Rocha',
      q_venda: 5,
      q_entrega_futura: 5,
      q_reserva: 3,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-03T10:00:00Z',
    },
    {
      projeto_item_id: 'pi009',
      produto_id: 'p006',
      produto: 'Pendente Industrial Black 5Lâmpadas',
      produto_codigo: 'PIB-05',
      projeto_id: 'pr009',
      projeto_codigo: 'OB-2024-029',
      orcamento_id: 'oc009',
      orcamento_numero: 'ORC-029',
      cliente_id: 'c009',
      cliente: 'Ricardo Fernandes',
      q_venda: 2,
      q_entrega_futura: 2,
      q_reserva: 0,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-02T15:10:00Z',
    },
  ],
  p007: [
    {
      projeto_item_id: 'pi010',
      produto_id: 'p007',
      produto: 'Trilho Eletrificado 3 Fases 1m',
      produto_codigo: 'TRF-1M',
      projeto_id: 'pr010',
      projeto_codigo: 'OB-2024-011',
      orcamento_id: 'oc010',
      orcamento_numero: 'ORC-011',
      cliente_id: 'c010',
      cliente: 'Loja Conceito Vista',
      q_venda: 12,
      q_entrega_futura: 12,
      q_reserva: 8,
      q_transferida_saida: 0,
      atualizado_em: '2026-07-01T09:00:00Z',
    },
  ],
  p008: [
    {
      projeto_item_id: 'pi011',
      produto_id: 'p008',
      produto: 'Driver LED 12V 150W',
      produto_codigo: 'DRV-150',
      projeto_id: 'pr011',
      projeto_codigo: 'OB-2024-016',
      orcamento_id: 'oc011',
      orcamento_numero: 'ORC-016',
      cliente_id: 'c011',
      cliente: 'Tecnologia Bright Ltda',
      q_venda: 11,
      q_entrega_futura: 11,
      q_reserva: 4,
      q_transferida_saida: 0,
      atualizado_em: '2026-06-30T14:20:00Z',
    },
  ],
}
